sonar.projectKey=typeorm_typeorm
sonar.organization=typeorm
sonar.sources=src
sonar.tests=test
sonar.exclusions=packages/**,docs/**
sonar.javascript.lcov.reportPaths=coverage-parts/**/lcov.info
sonar.qualitygate.wait=true
