name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/publish-docs.yml"

concurrency:
  group: publish-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Docs
    environment: docs
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build-docs

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/build --project-name=typeorm
